### PR TITLE
Allow users to configure how many lines to display

### PR DESCRIPTION
**Pull request by matugm**

### CODE REVIEW

**Comment by schneems** [comment]
Could you convert this to a flag instead, something like `--lines 35` ?

**Comment by matugm** [comment]
I added [Thor](http://whatisthor.com/) to parse the command-line options. I think that makes things a lot cleaner & opens things up for new features.

If you'd prefer not adding Thor I can do the `--lines` parsing manually, but it's not going to look pretty :)

**Comment by schneems** [comment]
Thanks! I like Thor in general. I’ll need to get to a computer to test this out. Looks good at a glance.

**Comment by schneems** [comment]
Sorry for the massive delay here. Thanks for the work! Merging in <3

**Pull request merged**
